/*
========================================
Atag Helpers v1.01 (sys 2.00)
========================================

Änderungen
- vollständig: alle vom Exporter benötigten Helper enthalten
- Markdown Sort ergänzt (fix für getSortedMarkdownItems Fehler)
- zentrale Wrapper + Bulk integriert
- keine Abhängigkeiten mehr außerhalb

Anwendung

bulkApplyTags() gibt ein result-Array zurück.
Dieses Array kann in weiteren bulkApplyTags()- oder bulkExportAtags()-Aufrufen wiederverwendet werden.

result = bulkApplyTags({
  textFields: ["Notiz", "Atag Aliases"],
  targetField: "tags",
  targetFieldType: "tags",
  preserveForeignTagsField: "Tags User",
  parserOwnedTagsField: "Tags Parser"
});

bulkApplyTags({
  textFields: ["Notiz", "Atag Aliases"],
  targetField: "Atag MD",
  targetFieldType: "md",
  result: result
});

========================================
*/

// ===== SYSTEM =====
var ATAG_SYS_VERSION = "2.00";

// ===== BASIC =====
function isAutoGeneratedName(name) {
  return /^(link|tel|mail|value)\d+$/i.test(String(name || ""));
}

function toNumberIfPossible(val) {
  if (val == null || val === "") return null;
  if (typeof val === "number") return isNaN(val) ? null : val;
  var s = String(val).trim().replace(",", ".");
  var n = Number(s);
  return isNaN(n) ? null : n;
}

function formatNumberLocale(n, decimals) {
  if (n == null || isNaN(n)) return "";
  var d = decimals == null ? 1 : decimals;
  return Number(n).toFixed(d).replace(".", ",");
}

// ===== META =====
function isLinkRaw(raw) {
  var s = String(raw || "").trim();
  return /^(https?|ftp|file):\/\/\S+$/i.test(s) ||
         /^www\./i.test(s) ||
         /^(?:[A-Za-z0-9\-]+\.)+[A-Za-z]{2,}/.test(s);
}

function isEmailRaw(raw) {
  return /^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/i.test(String(raw || ""));
}

function isTelRaw(raw) {
  var s = String(raw || "").trim();
  if (!/^\+?[0-9][0-9 ]+$/.test(s)) return false;
  var tel = s.replace(/ /g, "");
  return tel.replace(/^\+/, "").length >= 6;
}

function collectMetaTags(items) {
  var out = [], seen = {};
  for (var i = 0; i < items.length; i++) {
    var raw = items[i].rawText;
    if (isLinkRaw(raw) && !seen.link) { seen.link = 1; out.push("link"); }
    else if (isEmailRaw(raw) && !seen.email) { seen.email = 1; out.push("email"); }
    else if (isTelRaw(raw) && !seen.tel) { seen.tel = 1; out.push("tel"); }
  }
  return out;
}

// ===== TAG LIST =====
function uniqueTagNames(items, skipAuto) {
  var out = [], seen = {};
  for (var i = 0; i < items.length; i++) {
    var n = items[i].name;
    if (skipAuto && isAutoGeneratedName(n)) continue;
    var k = n.toLowerCase();
    if (!seen[k]) { seen[k] = 1; out.push(n); }
  }
  return out;
}

function mergeTagLists(a, b) {
  var out = [], seen = {};
  function add(x) {
    if (!x) return;
    var k = x.toLowerCase();
    if (!seen[k]) { seen[k] = 1; out.push(x); }
  }
  (a || []).forEach(add);
  (b || []).forEach(add);
  return out;
}

function subtractTagLists(src, rem) {
  var map = {}, out = [];
  (rem || []).forEach(r => map[String(r).toLowerCase()] = 1);
  (src || []).forEach(s => {
    if (!map[String(s).toLowerCase()]) out.push(s);
  });
  return out;
}

// ===== VALUE =====
function buildValueMap(items) {
  var map = {};
  items.forEach(it => {
    map[it.name] = it.attrValue != null ? it.attrValue : null;
  });
  return map;
}

// ===== MARKDOWN =====
function shortenMarkdownLabel(raw, maxLen) {
  var s = String(raw);
  s = s.replace(/^(https?:\/\/)/, "");
  return s.length <= maxLen ? s : s.substring(0, maxLen) + "...";
}

function formatMarkdownValue(name, val, raw) {
  if (val == null) return name;

  if (isLinkRaw(raw)) return name + ": [" + shortenMarkdownLabel(raw, 30) + "](" + raw + ")";
  if (isEmailRaw(raw)) return name + ": [" + raw + "](mailto:" + raw + ")";
  if (isTelRaw(raw)) return name + ": [" + raw + "](tel:" + raw.replace(/ /g, "") + ")";

  return name + ": " + val;
}

// ===== MARKDOWN SORT =====
function classifyMarkdownKind(raw) {
  var s = String(raw || "").trim();

  if (isLinkRaw(s)) return "link";
  if (isEmailRaw(s)) return "mail";
  if (isTelRaw(s)) return "tel";
  if (/^[+-]?\d+(?:[.,]\d+)?$/.test(s)) return "number";

  return "text";
}

function getMarkdownSortGroup(item) {
  if (!item || item.attrText == null || item.attrText === "") return 4;

  var kind = classifyMarkdownKind(item.rawText);

  if (kind === "link" || kind === "mail" || kind === "tel") return 1;
  if (kind === "number") return 2;
  if (kind === "text") return 3;

  return 4;
}

function getSortedMarkdownItems(items) {
  var g1 = [], g2 = [], g3 = [], g4 = [];

  for (var i = 0; i < items.length; i++) {
    var it = items[i];
    var group = getMarkdownSortGroup(it);

    if (group === 1) g1.push(it);
    else if (group === 2) g2.push(it);
    else if (group === 3) g3.push(it);
    else g4.push(it);
  }

  return g1.concat(g2, g3, g4);
}

// ===== ROW =====
function computeAggregate(values, mode) {
  if (!values.length) return null;
  if (mode === "sum") return values.reduce((a,b)=>a+b,0);
  if (mode === "avg") return values.reduce((a,b)=>a+b,0)/values.length;
  return null;
}

// ===== TABLE =====
function shortenTableWord(s, maxLen) {
  var str = String(s || "");
  var n = Number(maxLen);

  if (isNaN(n) || n < 0) return str;
  if (n === 0) n = 9;

  if (str.length <= n) return str;
  return str.substring(0, n) + ".";
}

// ===== HTML =====
function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g,"&amp;")
    .replace(/</g,"&lt;")
    .replace(/>/g,"&gt;")
    .replace(/"/g,"&quot;");
}

// ===== WRAPPER =====
function applyTags(cfg) {
  var entryObj = cfg.entryObj || entry();
  if (!entryObj) return;

  var result = cfg.result || collectAtags({
    entryObj: entryObj,
    textFields: cfg.textFields || [],
    excludeNames: cfg.excludeNames || []
  });

  exportAtags({
    entryObj: entryObj,
    result: result,
    targetField: cfg.targetField,
    targetFieldType: cfg.targetFieldType,
    mergeWithExistingTags: cfg.mergeWithExistingTags,
    preserveForeignTagsField: cfg.preserveForeignTagsField,
    parserOwnedTagsField: cfg.parserOwnedTagsField,
    rowAggregateMode: cfg.rowAggregateMode,
    rowIncludeUnits: cfg.rowIncludeUnits,
    rowAggregateDecimals: cfg.rowAggregateDecimals,
    shortenTableHeaders: cfg.shortenTableHeaders
  });

  return result;
}

// ===== BULK =====
function resolveBulkResult(externalResult, entryObj, index, allEntries) {
  if (typeof externalResult === "function") {
    return externalResult(entryObj, index, allEntries);
  }

  if (Array.isArray(externalResult)) {
    return externalResult[index] || null;
  }

  if (externalResult && typeof externalResult === "object") {
    return externalResult;
  }

  return null;
}

function bulkApplyTags(cfg) {
  var all = lib().entries();
  var externalResult = cfg ? cfg.result : null;
  var results = [];

  for (var i = 0; i < all.length; i++) {
    var e = all[i];
    var result = resolveBulkResult(externalResult, e, i, all);

    if (!result) {
      result = collectAtags({
        entryObj: e,
        textFields: cfg.textFields || [],
        excludeNames: cfg.excludeNames || []
      });
    }

    results.push(result);

    exportAtags({
      entryObj: e,
      result: result,
      targetField: cfg.targetField,
      targetFieldType: cfg.targetFieldType,
      mergeWithExistingTags: cfg.mergeWithExistingTags,
      preserveForeignTagsField: cfg.preserveForeignTagsField,
      parserOwnedTagsField: cfg.parserOwnedTagsField,
      rowAggregateMode: cfg.rowAggregateMode,
      rowIncludeUnits: cfg.rowIncludeUnits,
      rowAggregateDecimals: cfg.rowAggregateDecimals,
      shortenTableHeaders: cfg.shortenTableHeaders
    });
  }

  return results;
}

function bulkExportAtags(cfg) {
  var all = lib().entries();
  var externalResult = cfg ? cfg.result : null;
  var results = [];

  for (var i = 0; i < all.length; i++) {
    var e = all[i];
    var result = resolveBulkResult(externalResult, e, i, all);

    if (!result) {
      result = collectAtags({
        entryObj: e,
        textFields: cfg.textFields || [],
        excludeNames: cfg.excludeNames || []
      });
    }

    results.push(result);

    exportAtags({
      entryObj: e,
      result: result,
      targetField: cfg.targetField,
      targetFieldType: cfg.targetFieldType,
      mergeWithExistingTags: cfg.mergeWithExistingTags,
      preserveForeignTagsField: cfg.preserveForeignTagsField,
      parserOwnedTagsField: cfg.parserOwnedTagsField,
      rowAggregateMode: cfg.rowAggregateMode,
      rowIncludeUnits: cfg.rowIncludeUnits,
      rowAggregateDecimals: cfg.rowAggregateDecimals,
      shortenTableHeaders: cfg.shortenTableHeaders
    });
  }

  return results;
}
