/*
========================================
#3 Atag Helpers Lib v2.11 (sys 2.30)
========================================

Changes
- remote/library-safe helper module
- expose own library version function
- Memento entry/lib wrappers removed from this lib file
- aggregate helper supports min, max, max_abs, min_abs, add, avg, median, first, last and amount
- shared helpers for collect/export scripts
- editor-safe WSH JScript syntax
- JSON value maps keep repeated tag values as arrays
- markdown sorting treats category tags as their own group before blanks
- compute min/max/max_abs/min_abs aggregates without sorting

========================================
*/

// ===== SYSTEM =====
var ATAG_SYS_VERSION = "2.30";

function getHelpersLibVersion() {
  return {
    name: "helpers_lib",
    version: "2.11",
    sysVersion: ATAG_SYS_VERSION,
    path: "core_lib/helpers_lib.js"
  };
}

if (typeof registerAtagLibVersion === "function") {
  registerAtagLibVersion("helpers_lib", "2.11", ATAG_SYS_VERSION, "core_lib/helpers_lib.js");
}

// ===== BASIC =====
function trimAtagLibString(s) {
  return String(s || "").replace(/^\s+|\s+$/g, "");
}

function buildAtagLibQuoteState(str) {
  var s = String(str || "");
  var state = [];
  var inSingle = false;
  var inDouble = false;
  var i;
  var ch;

  for (i = 0; i <= s.length; i++) {
    state[i] = inSingle || inDouble;
    if (i >= s.length) break;

    ch = s.charAt(i);
    if (ch === "'" && !inDouble) inSingle = !inSingle;
    else if (ch === '"' && !inSingle) inDouble = !inDouble;
  }

  return state;
}

function isInsideAtagLibQuoteState(state, pos) {
  var p = Number(pos);
  if (!state || isNaN(p)) return false;
  if (p < 0) p = 0;
  if (p >= state.length) p = state.length - 1;
  return !!state[p];
}

function isAutoGeneratedName(name) {
  return /^(link|tel|mail|value)\d+$/i.test(String(name || ""));
}

function trimString(s) {
  return String(s || "").replace(/^\s+|\s+$/g, "");
}

function toNumberIfPossible(val) {
  if (val == null || val === "") return null;
  if (typeof val === "number") return isNaN(val) ? null : val;

  var s = trimString(val).replace(",", ".");
  var n = Number(s);
  return isNaN(n) ? null : n;
}

function formatNumberLocale(n, decimals) {
  if (n == null || isNaN(n)) return "";
  var d = decimals == null ? 1 : decimals;
  return Number(n).toFixed(d).replace(".", ",");
}

function isWholeNumber(n) {
  return typeof n === "number" && isFinite(n) && Math.floor(n) === n;
}

function itemHasDecimalValue(item) {
  if (!item) return false;

  var raw = item.attrText != null && item.attrText !== "" ? item.attrText : item.rawText;
  if (raw == null || raw === "") return false;

  return /[.,]\d+/.test(String(raw));
}

function formatTagNumberLocale(n, decimals, forceDecimal) {
  if (n == null || isNaN(n)) return "";
  if (!forceDecimal && isWholeNumber(Number(n))) return String(Number(n)).replace(".", ",");
  return formatNumberLocale(n, decimals);
}

// ===== META =====
function isLinkRaw(raw) {
  var s = trimString(raw);
  return /^(https?|ftp|file):\/\/\S+$/i.test(s) ||
         /^www\./i.test(s) ||
         /^(?:[A-Za-z0-9\-]+\.)+[A-Za-z]{2,}/.test(s);
}

function isEmailRaw(raw) {
  return /^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/i.test(String(raw || ""));
}

function isTelRaw(raw) {
  var s = trimString(raw);
  if (!/^\+?[0-9][0-9 ]+$/.test(s)) return false;
  var tel = s.replace(/ /g, "");
  return tel.replace(/^\+/, "").length >= 6;
}

function collectMetaTags(items) {
  var out = [];
  var seen = {};
  var i;
  var raw;

  for (i = 0; i < items.length; i++) {
    raw = items[i].rawText;
    if (isLinkRaw(raw) && !seen.link) {
      seen.link = 1;
      out.push("link");
    } else if (isEmailRaw(raw) && !seen.email) {
      seen.email = 1;
      out.push("email");
    } else if (isTelRaw(raw) && !seen.tel) {
      seen.tel = 1;
      out.push("tel");
    }
  }

  return out;
}

// ===== TAG LIST =====
function compareTagNames(a, b) {
  var aa = String(a || "");
  var bb = String(b || "");
  var al = aa.toLowerCase();
  var bl = bb.toLowerCase();

  if (al < bl) return -1;
  if (al > bl) return 1;
  if (aa < bb) return -1;
  if (aa > bb) return 1;
  return 0;
}

function sortTagNames(tags) {
  var out = (tags || []).slice(0);
  out.sort(compareTagNames);
  return out;
}

function sortItemsByTagName(items) {
  var out = (items || []).slice(0);
  out.sort(function(a, b) {
    return compareTagNames(a && a.name, b && b.name);
  });
  return out;
}

function uniqueTagNames(items, skipAuto) {
  var out = [];
  var seen = {};
  var i;
  var n;
  var k;

  for (i = 0; i < items.length; i++) {
    n = items[i].name;
    if (skipAuto && isAutoGeneratedName(n)) continue;
    k = String(n).toLowerCase();
    if (!seen[k]) {
      seen[k] = 1;
      out.push(n);
    }
  }

  return out;
}

function mergeTagLists(a, b) {
  var out = [];
  var seen = {};

  function add(x) {
    var k;
    if (!x) return;
    k = String(x).toLowerCase();
    if (!seen[k]) {
      seen[k] = 1;
      out.push(x);
    }
  }

  var i;
  for (i = 0; i < (a || []).length; i++) add(a[i]);
  for (i = 0; i < (b || []).length; i++) add(b[i]);

  return out;
}

function subtractTagLists(src, rem) {
  var map = {};
  var out = [];
  var i;
  var key;

  for (i = 0; i < (rem || []).length; i++) {
    key = String(rem[i]).toLowerCase();
    map[key] = 1;
  }

  for (i = 0; i < (src || []).length; i++) {
    key = String(src[i]).toLowerCase();
    if (!map[key]) out.push(src[i]);
  }

  return out;
}

// ===== VALUE =====
function buildValueMap(items) {
  var map = {};
  var i;
  var it;
  var val;

  for (i = 0; i < items.length; i++) {
    it = items[i];
    val = normalizeValueMapItemValue(it.attrValue, it);

    if (map.hasOwnProperty(it.name)) {
      if (!isArrayValue(map[it.name])) map[it.name] = [map[it.name]];
      map[it.name].push(val);
    } else {
      map[it.name] = val;
    }
  }

  return map;
}

function normalizeValueMapItemValue(val, item) {
  if (val == null) return null;
  if (item && (item.isCategory === true || item.kind === "category" || item.type === "category")) return val;
  if (isArrayValue(val)) return val.join(",");
  return val;
}

function escapeJsonString(s) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");
}

function stringifyJsonValue(val) {
  if (val == null) return "null";
  if (isArrayValue(val)) {
    var parts = [];
    for (var i = 0; i < val.length; i++) parts.push(stringifyJsonValue(val[i]));
    return "[" + parts.join(",") + "]";
  }
  if (typeof val === "number" || typeof val === "boolean") return String(val);
  return "\"" + escapeJsonString(val) + "\"";
}

function stringifyValueMap(map) {
  var keys = [];
  var out = [];
  var k;
  var i;

  for (k in map) {
    if (map.hasOwnProperty(k)) keys.push(k);
  }

  for (i = 0; i < keys.length; i++) {
    k = keys[i];
    out.push("\"" + escapeJsonString(k) + "\":" + stringifyJsonValue(map[k]));
  }

  return "{" + out.join(",") + "}";
}

// ===== MARKDOWN =====
function shortenMarkdownLabel(raw, maxLen) {
  var s = String(raw);
  s = s.replace(/^(https?:\/\/)/, "");
  if (s.length <= maxLen) return s;
  return s.substring(0, maxLen) + "...";
}

function formatMarkdownValue(name, val, raw) {
  if (val == null) return name;

  if (isLinkRaw(raw)) {
    return name + ": [" + shortenMarkdownLabel(raw, 30) + "](" + raw + ")";
  }
  if (isEmailRaw(raw)) {
    return name + ": [" + raw + "](mailto:" + raw + ")";
  }
  if (isTelRaw(raw)) {
    return name + ": [" + raw + "](tel:" + raw.replace(/ /g, "") + ")";
  }

  return name + ": " + val;
}

function isArrayValue(val) {
  return Object.prototype.toString.call(val) === "[object Array]";
}

function classifyMarkdownKind(item) {
  var raw = item ? item.rawText : "";
  var val = item ? item.attrValue : null;
  var s = trimString(raw);
  var n;

  if (item && (item.isCategory === true || item.kind === "category" || item.type === "category")) return "category";
  if (isLinkRaw(s)) return "link";
  if (isEmailRaw(s)) return "mail";
  if (isTelRaw(s)) return "tel";
  if (isArrayValue(val)) return "list";

  n = toNumberIfPossible(val);
  if (n != null || /^[+-]?\d+(?:[.,]\d+)?$/.test(s)) {
    if (itemHasDecimalValue(item)) return "real";
    return "int";
  }

  return "text";
}

function getMarkdownSortGroup(item) {
  var kind;
  if (!item || item.attrText == null || item.attrText === "") return 9;

  kind = classifyMarkdownKind(item);

  if (kind === "link") return 1;
  if (kind === "mail") return 2;
  if (kind === "tel") return 3;
  if (kind === "int") return 4;
  if (kind === "real") return 5;
  if (kind === "text") return 6;
  if (kind === "list") return 7;
  if (kind === "category") return 8;

  return 9;
}

function getSortedMarkdownItems(items) {
  var groups = [[], [], [], [], [], [], [], [], []];
  var i;
  var it;
  var group;
  var out = [];

  for (i = 0; i < items.length; i++) {
    it = items[i];
    group = getMarkdownSortGroup(it);
    groups[group - 1].push(it);
  }

  for (i = 0; i < groups.length; i++) {
    out = out.concat(sortItemsByTagName(groups[i]));
  }

  return out;
}

function markdownItemLabel(item, cfg) {
  var mode = cfg && cfg.markdownLabelNames ? String(cfg.markdownLabelNames).toLowerCase() : "long";
  var longName;
  var shortName;

  if (!item) return "";

  longName = String(item.name || "");
  shortName = String(item.displayName || item.name || "");

  if (mode === "short") return shortName || longName;
  if (mode === "both" && shortName && shortName !== longName) return shortName + " (" + longName + ")";
  return longName || shortName;
}

function compareMarkdownItems(a, b, cfg) {
  var ga = getMarkdownSortGroup(a);
  var gb = getMarkdownSortGroup(b);

  if (ga !== gb) return ga - gb;
  return compareTagNames(markdownItemLabel(a, cfg), markdownItemLabel(b, cfg));
}

// ===== ROW =====
function computeAggregate(values, mode) {
  var i;
  var sum;
  var sorted;
  var mid;
  var m = String(mode == null ? "avg" : mode).toLowerCase();
  var best;
  var d;

  if (!values.length) return null;

  if (m === "add") m = "sum";
  if (m === "amount" || m === "count") return values.length;
  if (m === "first") return values[0];
  if (m === "last") return values[values.length - 1];
  if (m === "min") {
    best = values[0];
    for (i = 1; i < values.length; i++) if (values[i] < best) best = values[i];
    return best;
  }
  if (m === "max") {
    best = values[0];
    for (i = 1; i < values.length; i++) if (values[i] > best) best = values[i];
    return best;
  }
  if (m === "max_abs" || m === "maxabs") {
    best = values[0];
    for (i = 1; i < values.length; i++) {
      d = Math.abs(values[i]) - Math.abs(best);
      if (d > 0 || (d === 0 && values[i] > best)) best = values[i];
    }
    return best;
  }
  if (m === "min_abs" || m === "minabs") {
    best = values[0];
    for (i = 1; i < values.length; i++) {
      d = Math.abs(values[i]) - Math.abs(best);
      if (d < 0 || (d === 0 && values[i] > best)) best = values[i];
    }
    return best;
  }
  if (m === "median") {
    sorted = values.slice(0);
    sorted.sort(function(a, b) { return a - b; });
    mid = Math.floor(sorted.length / 2);
    if (sorted.length % 2) return sorted[mid];
    return (sorted[mid - 1] + sorted[mid]) / 2;
  }

  if (m === "sum" || m === "avg") {
    sum = 0;
    for (i = 0; i < values.length; i++) sum += values[i];
    if (m === "sum") return sum;
    return sum / values.length;
  }

  return null;
}

// ===== TABLE =====
function shortenTableWord(s, maxLen) {
  var str = String(s || "");
  var n = Number(maxLen);

  if (isNaN(n) || n < 0) return str;
  if (n === 0) n = 10;

  if (str.length <= n) return str;
  return str.substring(0, n) + ".";
}

// ===== HTML =====
function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
