/*
========================================
A3 Atag Helpers v2.01 (sys 2.21)
========================================

Changes
- markdown/text exports use long tag names by default; short display names are opt-in
- pass includeBlankTags through export wrappers
- pass markdownGroupSeparator/markdownGroupSeparators through export wrappers
- sort markdown output by detailed value type groups
- enabled/collectResults accept 0/1 style values
- applyTags returns null when disabled
- shared helpers for collect/export scripts
- editor-safe WSH JScript syntax
- bulk helpers support `collectResults: false`
- wrappers support `enabled: false`
- pass tableHeaderNames through export wrappers
- JSON value maps keep repeated tag values as arrays
- markdown sorting treats category tags as their own group before blanks
- consolidate wrapper export config

========================================
*/

// ===== SYSTEM =====
var ATAG_SYS_VERSION = "2.21";

// ===== BASIC =====
function isAutoGeneratedName(name) {
  return /^(link|tel|mail|value)\d+$/i.test(String(name || ""));
}

function trimString(s) {
  return String(s || "").replace(/^\s+|\s+$/g, "");
}

function toNumberIfPossible(val) {
  if (val == null || val === "") return null;
  if (typeof val === "number") return isNaN(val) ? null : val;

  var s = trimString(val).replace(",", ".");
  var n = Number(s);
  return isNaN(n) ? null : n;
}

function formatNumberLocale(n, decimals) {
  if (n == null || isNaN(n)) return "";
  var d = decimals == null ? 1 : decimals;
  return Number(n).toFixed(d).replace(".", ",");
}

function isWholeNumber(n) {
  return typeof n === "number" && isFinite(n) && Math.floor(n) === n;
}

function itemHasDecimalValue(item) {
  if (!item) return false;

  var raw = item.attrText != null && item.attrText !== "" ? item.attrText : item.rawText;
  if (raw == null || raw === "") return false;

  return /[.,]\d+/.test(String(raw));
}

function formatTagNumberLocale(n, decimals, forceDecimal) {
  if (n == null || isNaN(n)) return "";
  if (!forceDecimal && isWholeNumber(Number(n))) return String(Number(n)).replace(".", ",");
  return formatNumberLocale(n, decimals);
}

// ===== META =====
function isLinkRaw(raw) {
  var s = trimString(raw);
  return /^(https?|ftp|file):\/\/\S+$/i.test(s) ||
         /^www\./i.test(s) ||
         /^(?:[A-Za-z0-9\-]+\.)+[A-Za-z]{2,}/.test(s);
}

function isEmailRaw(raw) {
  return /^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/i.test(String(raw || ""));
}

function isTelRaw(raw) {
  var s = trimString(raw);
  if (!/^\+?[0-9][0-9 ]+$/.test(s)) return false;
  var tel = s.replace(/ /g, "");
  return tel.replace(/^\+/, "").length >= 6;
}

function collectMetaTags(items) {
  var out = [];
  var seen = {};
  var i;
  var raw;

  for (i = 0; i < items.length; i++) {
    raw = items[i].rawText;
    if (isLinkRaw(raw) && !seen.link) {
      seen.link = 1;
      out.push("link");
    } else if (isEmailRaw(raw) && !seen.email) {
      seen.email = 1;
      out.push("email");
    } else if (isTelRaw(raw) && !seen.tel) {
      seen.tel = 1;
      out.push("tel");
    }
  }

  return out;
}

// ===== TAG LIST =====
function compareTagNames(a, b) {
  var aa = String(a || "");
  var bb = String(b || "");
  var al = aa.toLowerCase();
  var bl = bb.toLowerCase();

  if (al < bl) return -1;
  if (al > bl) return 1;
  if (aa < bb) return -1;
  if (aa > bb) return 1;
  return 0;
}

function sortTagNames(tags) {
  var out = (tags || []).slice(0);
  out.sort(compareTagNames);
  return out;
}

function sortItemsByTagName(items) {
  var out = (items || []).slice(0);
  out.sort(function(a, b) {
    return compareTagNames(a && a.name, b && b.name);
  });
  return out;
}

function uniqueTagNames(items, skipAuto) {
  var out = [];
  var seen = {};
  var i;
  var n;
  var k;

  for (i = 0; i < items.length; i++) {
    n = items[i].name;
    if (skipAuto && isAutoGeneratedName(n)) continue;
    k = String(n).toLowerCase();
    if (!seen[k]) {
      seen[k] = 1;
      out.push(n);
    }
  }

  return out;
}

function mergeTagLists(a, b) {
  var out = [];
  var seen = {};

  function add(x) {
    var k;
    if (!x) return;
    k = String(x).toLowerCase();
    if (!seen[k]) {
      seen[k] = 1;
      out.push(x);
    }
  }

  var i;
  for (i = 0; i < (a || []).length; i++) add(a[i]);
  for (i = 0; i < (b || []).length; i++) add(b[i]);

  return out;
}

function subtractTagLists(src, rem) {
  var map = {};
  var out = [];
  var i;
  var key;

  for (i = 0; i < (rem || []).length; i++) {
    key = String(rem[i]).toLowerCase();
    map[key] = 1;
  }

  for (i = 0; i < (src || []).length; i++) {
    key = String(src[i]).toLowerCase();
    if (!map[key]) out.push(src[i]);
  }

  return out;
}

// ===== VALUE =====
function buildValueMap(items) {
  var map = {};
  var i;
  var it;
  var val;

  for (i = 0; i < items.length; i++) {
    it = items[i];
    val = normalizeValueMapItemValue(it.attrValue);

    if (map.hasOwnProperty(it.name)) {
      if (!isArrayValue(map[it.name])) map[it.name] = [map[it.name]];
      map[it.name].push(val);
    } else {
      map[it.name] = val;
    }
  }

  return map;
}

function normalizeValueMapItemValue(val) {
  if (val == null) return null;
  if (isArrayValue(val)) return val.join(",");
  return val;
}

function escapeJsonString(s) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/"/g, "\\\"")
    .replace(/\r/g, "\\r")
    .replace(/\n/g, "\\n")
    .replace(/\t/g, "\\t");
}

function stringifyJsonValue(val) {
  if (val == null) return "null";
  if (isArrayValue(val)) {
    var parts = [];
    for (var i = 0; i < val.length; i++) parts.push(stringifyJsonValue(val[i]));
    return "[" + parts.join(",") + "]";
  }
  if (typeof val === "number" || typeof val === "boolean") return String(val);
  return "\"" + escapeJsonString(val) + "\"";
}

function stringifyValueMap(map) {
  var keys = [];
  var out = [];
  var k;
  var i;

  for (k in map) {
    if (map.hasOwnProperty(k)) keys.push(k);
  }

  for (i = 0; i < keys.length; i++) {
    k = keys[i];
    out.push("\"" + escapeJsonString(k) + "\":" + stringifyJsonValue(map[k]));
  }

  return "{" + out.join(",") + "}";
}

// ===== MARKDOWN =====
function shortenMarkdownLabel(raw, maxLen) {
  var s = String(raw);
  s = s.replace(/^(https?:\/\/)/, "");
  if (s.length <= maxLen) return s;
  return s.substring(0, maxLen) + "...";
}

function formatMarkdownValue(name, val, raw) {
  if (val == null) return name;

  if (isLinkRaw(raw)) {
    return name + ": [" + shortenMarkdownLabel(raw, 30) + "](" + raw + ")";
  }
  if (isEmailRaw(raw)) {
    return name + ": [" + raw + "](mailto:" + raw + ")";
  }
  if (isTelRaw(raw)) {
    return name + ": [" + raw + "](tel:" + raw.replace(/ /g, "") + ")";
  }

  return name + ": " + val;
}

function isArrayValue(val) {
  return Object.prototype.toString.call(val) === "[object Array]";
}

function classifyMarkdownKind(item) {
  var raw = item ? item.rawText : "";
  var val = item ? item.attrValue : null;
  var s = trimString(raw);
  var n;

  if (item && (item.isCategory === true || item.kind === "category" || item.type === "category")) return "category";
  if (isLinkRaw(s)) return "link";
  if (isEmailRaw(s)) return "mail";
  if (isTelRaw(s)) return "tel";
  if (isArrayValue(val)) return "list";

  n = toNumberIfPossible(val);
  if (n != null || /^[+-]?\d+(?:[.,]\d+)?$/.test(s)) {
    if (itemHasDecimalValue(item)) return "real";
    return "int";
  }

  return "text";
}

function getMarkdownSortGroup(item) {
  var kind;
  if (!item || item.attrText == null || item.attrText === "") return 9;

  kind = classifyMarkdownKind(item);

  if (kind === "link") return 1;
  if (kind === "mail") return 2;
  if (kind === "tel") return 3;
  if (kind === "int") return 4;
  if (kind === "real") return 5;
  if (kind === "text") return 6;
  if (kind === "list") return 7;
  if (kind === "category") return 8;

  return 9;
}

function getSortedMarkdownItems(items) {
  var groups = [[], [], [], [], [], [], [], [], []];
  var i;
  var it;
  var group;
  var out = [];

  for (i = 0; i < items.length; i++) {
    it = items[i];
    group = getMarkdownSortGroup(it);
    groups[group - 1].push(it);
  }

  for (i = 0; i < groups.length; i++) {
    out = out.concat(sortItemsByTagName(groups[i]));
  }

  return out;
}

function markdownItemLabel(item, cfg) {
  var mode = cfg && cfg.markdownLabelNames ? String(cfg.markdownLabelNames).toLowerCase() : "long";
  var longName;
  var shortName;

  if (!item) return "";

  longName = String(item.name || "");
  shortName = String(item.displayName || item.name || "");

  if (mode === "short") return shortName || longName;
  if (mode === "both" && shortName && shortName !== longName) return shortName + " (" + longName + ")";
  return longName || shortName;
}

function compareMarkdownItems(a, b, cfg) {
  var ga = getMarkdownSortGroup(a);
  var gb = getMarkdownSortGroup(b);

  if (ga !== gb) return ga - gb;
  return compareTagNames(markdownItemLabel(a, cfg), markdownItemLabel(b, cfg));
}

// ===== ROW =====
function computeAggregate(values, mode) {
  var i;
  var sum;

  if (!values.length) return null;

  if (mode === "sum" || mode === "avg") {
    sum = 0;
    for (i = 0; i < values.length; i++) sum += values[i];
    if (mode === "sum") return sum;
    return sum / values.length;
  }

  return null;
}

// ===== TABLE =====
function shortenTableWord(s, maxLen) {
  var str = String(s || "");
  var n = Number(maxLen);

  if (isNaN(n) || n < 0) return str;
  if (n === 0) n = 10;

  if (str.length <= n) return str;
  return str.substring(0, n) + ".";
}

// ===== HTML =====
function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ===== WRAPPER =====
function exportAtagsFromCfg(cfg, entryObj, result) {
  exportAtags({
    entryObj: entryObj,
    result: result,
    targetField: cfg.targetField,
    targetFieldType: cfg.targetFieldType,
    mergeWithExistingTags: cfg.mergeWithExistingTags,
    preserveForeignTagsField: cfg.preserveForeignTagsField,
    parserOwnedTagsField: cfg.parserOwnedTagsField,
    rowAggregateMode: cfg.rowAggregateMode,
    rowIncludeUnits: cfg.rowIncludeUnits,
    rowAggregateDecimals: cfg.rowAggregateDecimals,
    shortenTableHeaders: cfg.shortenTableHeaders,
    tableHeaderNames: cfg.tableHeaderNames,
    markdownLabelNames: cfg.markdownLabelNames,
    includeBlankTags: cfg.includeBlankTags,
    markdownGroupSeparators: cfg.markdownGroupSeparators,
    markdownGroupSeparator: cfg.markdownGroupSeparator
  });
}

function collectAtagsFromCfg(cfg, entryObj) {
  return collectAtags({
    entryObj: entryObj,
    textFields: cfg.textFields || [],
    excludeNames: cfg.excludeNames || []
  });
}

function isCfgDisabled(cfg) {
  var v = cfg ? cfg.enabled : null;
  if (v === false || v === 0) return true;
  v = String(v == null ? "" : v).toLowerCase();
  return v === "0" || v === "false" || v === "no" || v === "off";
}

function isCfgCollectResultsEnabled(cfg) {
  var v = cfg ? cfg.collectResults : null;
  if (v === false || v === 0) return false;
  v = String(v == null ? "" : v).toLowerCase();
  return !(v === "0" || v === "false" || v === "no" || v === "off");
}

function applyTags(cfg) {
  cfg = cfg || {};
  if (isCfgDisabled(cfg)) return null;

  var entryObj = cfg.entryObj || entry();
  var result;

  if (!entryObj) return;

  result = cfg.result || collectAtagsFromCfg(cfg, entryObj);
  exportAtagsFromCfg(cfg, entryObj, result);

  return result;
}

// ===== BULK =====
function resolveBulkResult(externalResult, entryObj, index, allEntries) {
  if (typeof externalResult === "function") {
    return externalResult(entryObj, index, allEntries);
  }

  if (Array.isArray(externalResult)) {
    return externalResult[index] || null;
  }

  if (externalResult && typeof externalResult === "object") {
    return externalResult;
  }

  return null;
}

function bulkApplyTags(cfg) {
  cfg = cfg || {};
  if (isCfgDisabled(cfg)) return isCfgCollectResultsEnabled(cfg) ? [] : null;

  var all = lib().entries();
  var externalResult = cfg.result;
  var collectResults = isCfgCollectResultsEnabled(cfg);
  var results = collectResults ? [] : null;
  var i;
  var e;
  var result;

  for (i = 0; i < all.length; i++) {
    e = all[i];
    result = resolveBulkResult(externalResult, e, i, all);

    if (!result) result = collectAtagsFromCfg(cfg, e);
    if (collectResults) results.push(result);
    exportAtagsFromCfg(cfg, e, result);
  }

  return results;
}

function bulkExportAtags(cfg) {
  cfg = cfg || {};
  if (isCfgDisabled(cfg)) return isCfgCollectResultsEnabled(cfg) ? [] : null;

  var all = lib().entries();
  var externalResult = cfg.result;
  var collectResults = isCfgCollectResultsEnabled(cfg);
  var results = collectResults ? [] : null;
  var i;
  var e;
  var result;

  for (i = 0; i < all.length; i++) {
    e = all[i];
    result = resolveBulkResult(externalResult, e, i, all);

    if (!result) result = collectAtagsFromCfg(cfg, e);
    if (collectResults) results.push(result);
    exportAtagsFromCfg(cfg, e, result);
  }

  return results;
}
