/*
========================================
Atag Helpers v1.06 (sys 2.00)
========================================

Changes
- bulk helpers can skip collecting result arrays via `collectResults: false`
- add number-format helpers for integer-aware exports
- rebuilt from the last editor-safe helper version
- kept current export-required helpers, but simplified source structure
- removed compact arrow-heavy helper code to stay friendlier to the MDB editor

========================================
*/

// ===== SYSTEM =====
var ATAG_SYS_VERSION = "2.00";

// ===== BASIC =====
function isAutoGeneratedName(name) {
  return /^(link|tel|mail|value)\d+$/i.test(String(name || ""));
}

function toNumberIfPossible(val) {
  if (val == null || val === "") return null;
  if (typeof val === "number") return isNaN(val) ? null : val;

  var s = String(val).trim().replace(",", ".");
  var n = Number(s);
  return isNaN(n) ? null : n;
}

function formatNumberLocale(n, decimals) {
  if (n == null || isNaN(n)) return "";
  var d = decimals == null ? 1 : decimals;
  return Number(n).toFixed(d).replace(".", ",");
}

function isWholeNumber(n) {
  return typeof n === "number" && isFinite(n) && Math.floor(n) === n;
}

function itemHasDecimalValue(item) {
  if (!item) return false;

  var raw = item.attrText != null && item.attrText !== "" ? item.attrText : item.rawText;
  if (raw == null || raw === "") return false;

  return /[.,]\d+/.test(String(raw));
}

function formatTagNumberLocale(n, decimals, forceDecimal) {
  if (n == null || isNaN(n)) return "";
  if (!forceDecimal && isWholeNumber(Number(n))) return String(Number(n)).replace(".", ",");
  return formatNumberLocale(n, decimals);
}

// ===== META =====
function isLinkRaw(raw) {
  var s = String(raw || "").trim();
  return /^(https?|ftp|file):\/\/\S+$/i.test(s) ||
         /^www\./i.test(s) ||
         /^(?:[A-Za-z0-9\-]+\.)+[A-Za-z]{2,}/.test(s);
}

function isEmailRaw(raw) {
  return /^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$/i.test(String(raw || ""));
}

function isTelRaw(raw) {
  var s = String(raw || "").trim();
  if (!/^\+?[0-9][0-9 ]+$/.test(s)) return false;
  var tel = s.replace(/ /g, "");
  return tel.replace(/^\+/, "").length >= 6;
}

function collectMetaTags(items) {
  var out = [];
  var seen = {};
  var i;
  var raw;

  for (i = 0; i < items.length; i++) {
    raw = items[i].rawText;
    if (isLinkRaw(raw) && !seen.link) {
      seen.link = 1;
      out.push("link");
    } else if (isEmailRaw(raw) && !seen.email) {
      seen.email = 1;
      out.push("email");
    } else if (isTelRaw(raw) && !seen.tel) {
      seen.tel = 1;
      out.push("tel");
    }
  }

  return out;
}

// ===== TAG LIST =====
function uniqueTagNames(items, skipAuto) {
  var out = [];
  var seen = {};
  var i;
  var n;
  var k;

  for (i = 0; i < items.length; i++) {
    n = items[i].name;
    if (skipAuto && isAutoGeneratedName(n)) continue;
    k = String(n).toLowerCase();
    if (!seen[k]) {
      seen[k] = 1;
      out.push(n);
    }
  }

  return out;
}

function mergeTagLists(a, b) {
  var out = [];
  var seen = {};

  function add(x) {
    var k;
    if (!x) return;
    k = String(x).toLowerCase();
    if (!seen[k]) {
      seen[k] = 1;
      out.push(x);
    }
  }

  var i;
  for (i = 0; i < (a || []).length; i++) add(a[i]);
  for (i = 0; i < (b || []).length; i++) add(b[i]);

  return out;
}

function subtractTagLists(src, rem) {
  var map = {};
  var out = [];
  var i;
  var key;

  for (i = 0; i < (rem || []).length; i++) {
    key = String(rem[i]).toLowerCase();
    map[key] = 1;
  }

  for (i = 0; i < (src || []).length; i++) {
    key = String(src[i]).toLowerCase();
    if (!map[key]) out.push(src[i]);
  }

  return out;
}

// ===== VALUE =====
function buildValueMap(items) {
  var map = {};
  var i;
  var it;

  for (i = 0; i < items.length; i++) {
    it = items[i];
    map[it.name] = it.attrValue != null ? it.attrValue : null;
  }

  return map;
}

// ===== MARKDOWN =====
function shortenMarkdownLabel(raw, maxLen) {
  var s = String(raw);
  s = s.replace(/^(https?:\/\/)/, "");
  if (s.length <= maxLen) return s;
  return s.substring(0, maxLen) + "...";
}

function formatMarkdownValue(name, val, raw) {
  if (val == null) return name;

  if (isLinkRaw(raw)) {
    return name + ": [" + shortenMarkdownLabel(raw, 30) + "](" + raw + ")";
  }
  if (isEmailRaw(raw)) {
    return name + ": [" + raw + "](mailto:" + raw + ")";
  }
  if (isTelRaw(raw)) {
    return name + ": [" + raw + "](tel:" + raw.replace(/ /g, "") + ")";
  }

  return name + ": " + val;
}

function classifyMarkdownKind(raw) {
  var s = String(raw || "").trim();

  if (isLinkRaw(s)) return "link";
  if (isEmailRaw(s)) return "mail";
  if (isTelRaw(s)) return "tel";
  if (/^[+-]?\d+(?:[.,]\d+)?$/.test(s)) return "number";

  return "text";
}

function getMarkdownSortGroup(item) {
  var kind;
  if (!item || item.attrText == null || item.attrText === "") return 4;

  kind = classifyMarkdownKind(item.rawText);

  if (kind === "link" || kind === "mail" || kind === "tel") return 1;
  if (kind === "number") return 2;
  if (kind === "text") return 3;

  return 4;
}

function getSortedMarkdownItems(items) {
  var g1 = [];
  var g2 = [];
  var g3 = [];
  var g4 = [];
  var i;
  var it;
  var group;

  for (i = 0; i < items.length; i++) {
    it = items[i];
    group = getMarkdownSortGroup(it);

    if (group === 1) g1.push(it);
    else if (group === 2) g2.push(it);
    else if (group === 3) g3.push(it);
    else g4.push(it);
  }

  return g1.concat(g2, g3, g4);
}

// ===== ROW =====
function computeAggregate(values, mode) {
  var i;
  var sum;

  if (!values.length) return null;

  if (mode === "sum" || mode === "avg") {
    sum = 0;
    for (i = 0; i < values.length; i++) sum += values[i];
    if (mode === "sum") return sum;
    return sum / values.length;
  }

  return null;
}

// ===== TABLE =====
function shortenTableWord(s, maxLen) {
  var str = String(s || "");
  var n = Number(maxLen);

  if (isNaN(n) || n < 0) return str;
  if (n === 0) n = 10;

  if (str.length <= n) return str;
  return str.substring(0, n) + ".";
}

// ===== HTML =====
function escapeHtml(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

// ===== WRAPPER =====
function applyTags(cfg) {
  var entryObj = cfg.entryObj || entry();
  var result;

  if (!entryObj) return;

  result = cfg.result || collectAtags({
    entryObj: entryObj,
    textFields: cfg.textFields || [],
    excludeNames: cfg.excludeNames || []
  });

  exportAtags({
    entryObj: entryObj,
    result: result,
    targetField: cfg.targetField,
    targetFieldType: cfg.targetFieldType,
    mergeWithExistingTags: cfg.mergeWithExistingTags,
    preserveForeignTagsField: cfg.preserveForeignTagsField,
    parserOwnedTagsField: cfg.parserOwnedTagsField,
    rowAggregateMode: cfg.rowAggregateMode,
    rowIncludeUnits: cfg.rowIncludeUnits,
    rowAggregateDecimals: cfg.rowAggregateDecimals,
    shortenTableHeaders: cfg.shortenTableHeaders
  });

  return result;
}

// ===== BULK =====
function resolveBulkResult(externalResult, entryObj, index, allEntries) {
  if (typeof externalResult === "function") {
    return externalResult(entryObj, index, allEntries);
  }

  if (Array.isArray(externalResult)) {
    return externalResult[index] || null;
  }

  if (externalResult && typeof externalResult === "object") {
    return externalResult;
  }

  return null;
}

function bulkApplyTags(cfg) {
  cfg = cfg || {};
  var all = lib().entries();
  var externalResult = cfg.result;
  var collectResults = cfg.collectResults !== false;
  var results = collectResults ? [] : null;
  var i;
  var e;
  var result;

  for (i = 0; i < all.length; i++) {
    e = all[i];
    result = resolveBulkResult(externalResult, e, i, all);

    if (!result) {
      result = collectAtags({
        entryObj: e,
        textFields: cfg.textFields || [],
        excludeNames: cfg.excludeNames || []
      });
    }

    if (collectResults) results.push(result);

    exportAtags({
      entryObj: e,
      result: result,
      targetField: cfg.targetField,
      targetFieldType: cfg.targetFieldType,
      mergeWithExistingTags: cfg.mergeWithExistingTags,
      preserveForeignTagsField: cfg.preserveForeignTagsField,
      parserOwnedTagsField: cfg.parserOwnedTagsField,
      rowAggregateMode: cfg.rowAggregateMode,
      rowIncludeUnits: cfg.rowIncludeUnits,
      rowAggregateDecimals: cfg.rowAggregateDecimals,
      shortenTableHeaders: cfg.shortenTableHeaders
    });
  }

  return results;
}

function bulkExportAtags(cfg) {
  cfg = cfg || {};
  var all = lib().entries();
  var externalResult = cfg.result;
  var collectResults = cfg.collectResults !== false;
  var results = collectResults ? [] : null;
  var i;
  var e;
  var result;

  for (i = 0; i < all.length; i++) {
    e = all[i];
    result = resolveBulkResult(externalResult, e, i, all);

    if (!result) {
      result = collectAtags({
        entryObj: e,
        textFields: cfg.textFields || [],
        excludeNames: cfg.excludeNames || []
      });
    }

    if (collectResults) results.push(result);

    exportAtags({
      entryObj: e,
      result: result,
      targetField: cfg.targetField,
      targetFieldType: cfg.targetFieldType,
      mergeWithExistingTags: cfg.mergeWithExistingTags,
      preserveForeignTagsField: cfg.preserveForeignTagsField,
      parserOwnedTagsField: cfg.parserOwnedTagsField,
      rowAggregateMode: cfg.rowAggregateMode,
      rowIncludeUnits: cfg.rowIncludeUnits,
      rowAggregateDecimals: cfg.rowAggregateDecimals,
      shortenTableHeaders: cfg.shortenTableHeaders
    });
  }

  return results;
}
